# Generated by Django 5.0.7 on 2024-07-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ns',
        ),
        migrations.DeleteModel(
            name='pl',
        ),
        migrations.DeleteModel(
            name='rd',
        ),
        migrations.DeleteModel(
            name='wp',
        ),
    ]
