# Generated by Django 5.0.7 on 2024-07-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilsapp', '0002_delete_ns_delete_pl_delete_rd_delete_wp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='osmpop',
        ),
        migrations.DeleteModel(
            name='osmrd',
        ),
    ]
