# Generated by Django 5.0.7 on 2024-07-13 10:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilsapp', '0003_delete_osmpop_delete_osmrd'),
    ]

    operations = [
        migrations.CreateModel(
            name='osmpop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=12, null=True)),
                ('code', models.IntegerField(null=True)),
                ('fclass', models.CharField(max_length=28, null=True)),
                ('population', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='osmrd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=12, null=True)),
                ('code', models.IntegerField(null=True)),
                ('fclass', models.CharField(max_length=28, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('ref', models.CharField(max_length=20, null=True)),
                ('oneway', models.CharField(max_length=1, null=True)),
                ('maxspeed', models.IntegerField(null=True)),
                ('layer', models.BigIntegerField(null=True)),
                ('bridge', models.CharField(max_length=1, null=True)),
                ('tunnel', models.CharField(max_length=1, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='osmb',
        ),
    ]
