# Generated by Django 5.0.7 on 2024-07-13 10:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilsapp', '0004_osmpop_osmrd_delete_osmb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=254, null=True)),
                ('client_gov', models.CharField(max_length=254, null=True)),
                ('handle', models.CharField(max_length=16, null=True)),
                ('layer', models.CharField(max_length=254, null=True)),
                ('lyrhandle', models.CharField(max_length=16, null=True)),
                ('elevation', models.FloatField(null=True)),
                ('refname', models.CharField(max_length=254, null=True)),
                ('docname', models.CharField(max_length=254, null=True)),
                ('docpath', models.CharField(max_length=254, null=True)),
                ('doctype', models.CharField(max_length=32, null=True)),
                ('docver', models.CharField(max_length=16, null=True)),
                ('docupdate', models.DateField(null=True)),
                ('globalwidt', models.FloatField(null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='osmb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=12, null=True)),
                ('code', models.IntegerField(null=True)),
                ('fclass', models.CharField(max_length=28, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='pl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=254, null=True)),
                ('client_gov', models.CharField(max_length=254, null=True)),
                ('handle', models.CharField(max_length=16, null=True)),
                ('layer', models.CharField(max_length=254, null=True)),
                ('lyrhandle', models.CharField(max_length=16, null=True)),
                ('elevation', models.FloatField(null=True)),
                ('refname', models.CharField(max_length=254, null=True)),
                ('docname', models.CharField(max_length=254, null=True)),
                ('doctype', models.CharField(max_length=32, null=True)),
                ('docver', models.CharField(max_length=16, null=True)),
                ('docupdate', models.DateField(null=True)),
                ('globalwidt', models.FloatField(null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='rd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=254, null=True)),
                ('client_gov', models.CharField(max_length=254, null=True)),
                ('handle', models.CharField(max_length=16, null=True)),
                ('layer', models.CharField(max_length=254, null=True)),
                ('lyrhandle', models.CharField(max_length=16, null=True)),
                ('elevation', models.FloatField(null=True)),
                ('refname', models.CharField(max_length=254, null=True)),
                ('docname', models.CharField(max_length=254, null=True)),
                ('doctype', models.CharField(max_length=32, null=True)),
                ('docver', models.CharField(max_length=16, null=True)),
                ('docupdate', models.DateField(null=True)),
                ('globalwidt', models.FloatField(null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='wp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=254, null=True)),
                ('client_gov', models.CharField(max_length=254, null=True)),
                ('handle', models.CharField(max_length=16, null=True)),
                ('layer', models.CharField(max_length=254, null=True)),
                ('lyrhandle', models.CharField(max_length=16, null=True)),
                ('elevation', models.FloatField(null=True)),
                ('refname', models.CharField(max_length=254, null=True)),
                ('docname', models.CharField(max_length=254, null=True)),
                ('doctype', models.CharField(max_length=32, null=True)),
                ('docver', models.CharField(max_length=16, null=True)),
                ('docupdate', models.DateField(null=True)),
                ('globalwidt', models.FloatField(null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
