# Generated by Django 5.0.7 on 2024-07-14 17:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilsapp', '0005_ns_osmb_pl_rd_wp'),
    ]

    operations = [
        migrations.CreateModel(
            name='mh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=16, null=True)),
                ('handle', models.CharField(max_length=16, null=True)),
                ('layer', models.CharField(max_length=254, null=True)),
                ('elevation', models.FloatField(null=True)),
                ('refname', models.CharField(max_length=254, null=True)),
                ('docupdate', models.DateField(null=True)),
                ('docid', models.FloatField(null=True)),
                ('globalwidt', models.FloatField(null=True)),
                ('name', models.CharField(max_length=254, null=True)),
                ('length', models.CharField(max_length=254, null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=254, null=True)),
                ('client_gov', models.CharField(max_length=254, null=True)),
                ('handle', models.CharField(max_length=16, null=True)),
                ('layer', models.CharField(max_length=254, null=True)),
                ('elevation', models.FloatField(null=True)),
                ('refname', models.CharField(max_length=254, null=True)),
                ('docname', models.CharField(max_length=254, null=True)),
                ('doctype', models.CharField(max_length=32, null=True)),
                ('docver', models.CharField(max_length=16, null=True)),
                ('docupdate', models.DateField(null=True)),
                ('docid', models.FloatField(null=True)),
                ('globalwidt', models.FloatField(null=True)),
                ('length', models.CharField(max_length=254, null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='osmb',
        ),
        migrations.DeleteModel(
            name='osmpop',
        ),
        migrations.DeleteModel(
            name='osmrd',
        ),
    ]
