# Generated by Django 5.0.7 on 2024-07-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilsapp', '0008_remove_row_length_mh_bearing_mh_color_mh_enclosed_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='row',
            old_name='docver',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='docname',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='row',
            name='doctype',
        ),
        migrations.RemoveField(
            model_name='row',
            name='lyrhandle',
        ),
        migrations.AddField(
            model_name='row',
            name='bearing',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='row',
            name='color',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='row',
            name='docid',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='row',
            name='enclosed_a',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='row',
            name='linetype',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='row',
            name='linewt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='row',
            name='lyrfrzn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='row',
            name='lyron',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='row',
            name='name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
