# Generated by Django 5.0.6 on 2024-07-09 17:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=254, null=True)),
                ('client_gov', models.CharField(max_length=254, null=True)),
                ('handle', models.CharField(max_length=16, null=True)),
                ('layer', models.CharField(max_length=254, null=True)),
                ('lyrhandle', models.CharField(max_length=16, null=True)),
                ('elevation', models.FloatField(null=True)),
                ('refname', models.CharField(max_length=254, null=True)),
                ('docname', models.CharField(max_length=254, null=True)),
                ('docpath', models.CharField(max_length=254, null=True)),
                ('doctype', models.CharField(max_length=32, null=True)),
                ('docver', models.CharField(max_length=16, null=True)),
                ('docupdate', models.DateField(null=True)),
                ('globalwidt', models.FloatField(null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='pl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=254, null=True)),
                ('client_gov', models.CharField(max_length=254, null=True)),
                ('handle', models.CharField(max_length=16, null=True)),
                ('layer', models.CharField(max_length=254, null=True)),
                ('lyrhandle', models.CharField(max_length=16, null=True)),
                ('elevation', models.FloatField(null=True)),
                ('refname', models.CharField(max_length=254, null=True)),
                ('docname', models.CharField(max_length=254, null=True)),
                ('doctype', models.CharField(max_length=32, null=True)),
                ('docver', models.CharField(max_length=16, null=True)),
                ('docupdate', models.DateField(null=True)),
                ('globalwidt', models.FloatField(null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='rd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=254, null=True)),
                ('client_gov', models.CharField(max_length=254, null=True)),
                ('handle', models.CharField(max_length=16, null=True)),
                ('layer', models.CharField(max_length=254, null=True)),
                ('lyrhandle', models.CharField(max_length=16, null=True)),
                ('elevation', models.FloatField(null=True)),
                ('refname', models.CharField(max_length=254, null=True)),
                ('docname', models.CharField(max_length=254, null=True)),
                ('doctype', models.CharField(max_length=32, null=True)),
                ('docver', models.CharField(max_length=16, null=True)),
                ('docupdate', models.DateField(null=True)),
                ('globalwidt', models.FloatField(null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='wp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=254, null=True)),
                ('client_gov', models.CharField(max_length=254, null=True)),
                ('handle', models.CharField(max_length=16, null=True)),
                ('layer', models.CharField(max_length=254, null=True)),
                ('lyrhandle', models.CharField(max_length=16, null=True)),
                ('elevation', models.FloatField(null=True)),
                ('refname', models.CharField(max_length=254, null=True)),
                ('docname', models.CharField(max_length=254, null=True)),
                ('doctype', models.CharField(max_length=32, null=True)),
                ('docver', models.CharField(max_length=16, null=True)),
                ('docupdate', models.DateField(null=True)),
                ('globalwidt', models.FloatField(null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
